version: '2.8'

services:

  django:
    container_name: django
    build:
      context: ./myproject
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
    - 8000:8000
    volumes:
    - ./myproject:/usr/src/app
    depends_on:
    - celery
  
  rmq:
    container_name: rmq
    image: rabbitmq:3.12-management-alpine
    ports:
    - 5672:5672
    - 15672:15672
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
    - mongo

  celery:
    container_name: celery
    build:
      context: ./myproject
    command: celery --app=myproject worker -l INFO -Q task
    volumes:
    - ./myproject:/usr/src/app
    depends_on:
    - mongo
    - rmq

  flower:
    container_name: flower
    image: mher/flower
    ports:
    - 5555:5555
    environment:
    - CELERY_BROKER_URL=amqp://guest:guest@rmq:5672
    depends_on:
    - celery
